### PR TITLE
Add support for to_presentation

### PR DESCRIPTION
**Pull request by Joseph-Edwards**
This PR adds the bindings, documentation and tests for the `to_presentation` and `to_inverse_presentation` functions.

### CODE REVIEW

**Comment by Joseph-Edwards** [comment]
The majority of the commits in this PR come from #173, and this will be rebased once #173 is merged.

Most of the tests will fail until the corresponding [Presentation](https://github.com/libsemigroups/libsemigroups/pull/551) and [to_presentation](https://github.com/libsemigroups/libsemigroups/pull/555) are merged in `libsemigroups`.

**Comment by james-d-mitchell** [comment]
@Joseph-Edwards can you rebase this please?

**Comment by james-d-mitchell** [comment]
It seems that some thing has gone wrong with the ci @Joseph-Edwards, please let me know if you'd like me to try and fix it!

**Comment by Joseph-Edwards** [comment]
> It seems that some thing has gone wrong with the ci @Joseph-Edwards, please let me know if you'd like me to try and fix it!

I'll give it a go, but may call upon you if I'm not having any luck

**Comment by Joseph-Edwards** [comment]
After a bit of trawling, I came across [this discussion](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/345) about `pkg_resources` problems in `sphinxcontrib-bibtex`. The work around is apparently to install `setuptools` (though it's not immediately clear to me where that should be installed).

Before I could do that, the tests started passing again. Since they were passing before and the failures seem like a one-off, I'm not going to change anything. If this becomes a recurring issue, I'll look into it again.

**Pull request merged**
